version: "3"
services:
  app:
    build:
      args:
        user: saliou
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: appartement
    container_name: appartement-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - appartement

  db:
    image: mysql:5.7
    container_name: appartement-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - appartement

  nginx:
    image: nginx:alpine
    container_name: appartement-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - appartement

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    networks:
      - appartement
    depends_on:
      - db


networks:
  appartement:
    driver: bridge
